all: libmath libcallsite libarray classorder struct

libmath:
	$(MAKE) -C lib/libmath/v1
	$(MAKE) -C lib/libmath/v2

libcallsite:
	$(MAKE) -C lib/callsite/v1
	$(MAKE) -C lib/callsite/v2
	
libarray:
	$(MAKE) -C lib/array/v1
	$(MAKE) -C lib/array/v2

classorder:
	$(MAKE) -C lib/classorder/v1
	$(MAKE) -C lib/classorder/v2
	
struct:
	$(MAKE) -C lib/struct/v1
	$(MAKE) -C lib/struct/v2
