all: libmath libcallsite libarray

libmath:
	$(MAKE) -C lib/libmath/v1
	$(MAKE) -C lib/libmath/v2

libcallsite:
	$(MAKE) -C lib/callsite/v1
	$(MAKE) -C lib/callsite/v2
	
libarray:
	$(MAKE) -C lib/array/v1
	$(MAKE) -C lib/array/v2
