name: Update Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name comp

      - name: Install Compspec and Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          root=$PWD
          source activate comp
          cd /tmp
          git clone https://github.com/compspec/compspec
          cd compspec
          pip install -e .
          cd docs/
          pip install -r requirements.txt
          rm spec.md
          wget https://raw.githubusercontent.com/compspec/spec/main/spec.md
          make html
          cp -R $root/.git _build/html/.git
          rm -rf $root
          mv _build/html $root
          cd $root
          touch .nojekyll
          ls

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
