name: CI

on:
  push:
    branches:
      - main
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup black linter
      run: conda create --quiet --name black pyflakes

    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: ./docs/getting_started/*.rst ./docs/index.rst ./docs/getting_started/asp/*.rst ./docs/getting_started/compatibility/*.rst

    - name: Lint and format Python code
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate black
        pip install -r .github/dev-requirements.txt
        pre-commit run --all-files

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Test Composition Specs
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -e .[all]
          # Test examples
          python examples/asp/basic-graph/run.py
          python examples/asp/basic-diff/run.py
          python examples/asp/combine-graphs/run.py
          python examples/asp/python/tensorflow-example.py
          python examples/asp/python/tensorflow-module-example.py
          python examples/asp/python/tensorflow-function-example.py
          python examples/asp/spack/example-python.py
          python examples/asp/spack/example-singularity.py
          pip install -r examples/asp/dicom/requirements.txt
          python examples/asp/dicom/run.py
